### ISSUE TITLE
Example Config Doesn't Work Out of Box

### ISSUE THREAD

**Issue by mhamrah** [NvChad/example_config#20]
I'm trying learn nv chad and set up a clean install. I wanted to use this to kickstart lsp and other customizations, and I cloned this into the lua/custom directory. When doing a packersync I get the following error:

<img width="894" alt="image" src="https://user-images.githubusercontent.com/91162/224585070-13f6d589-0aa9-4240-89c9-7c9e73a97214.png">

but not sure how to debug. Hoping someone can point me in the right direction. 

TY

**Comment by siduck** [comment]
@mhamrah that example_config is for v2.0 nvchad only

**Comment by siduck** [comment]
you seem to use main branch nvchad

**Comment by mhamrah** [comment]
Thank you, I followed the install instructions which pulls from main. Happy
to submit a PR for docs if you feel this should be corrected.

**Comment by siduck** [comment]
which install instructions? I think i removed outdated stuff from the docs

**Comment by mhamrah** [comment]
<img width="738" alt="image" src="https://user-images.githubusercontent.com/91162/224836656-0f4e2889-ee35-4faa-925c-35d0fbd0cf62.png">

Which I assume pulls from the default branch, 'main'

**Comment by mhamrah** [comment]
apologies, this may have been unfortunate timing on my part from when I pulled nvchad and tried the custom configs.
