### ISSUE TITLE
Question about plugins in v2.0

### ISSUE THREAD

**Issue by kumkee** [NvChad/example_config#25]
[In v1.0 I installed](https://github.com/kumkee/nvchad_config/blob/v1.0/custom/plugins/init.lua#L7,L12) `numirias/semshi` like
```
  ["numirias/semshi"] = {
    ft = 'python',
    config = 'vim.cmd [[UpdateRemotePlugins]]',
  },
```
In v2.0 I attempted
```
{
    "numirias/semshi",
    ft = 'python',
    config = 'vim.cmd [[UpdateRemotePlugins]]',
}
```

but it complains 
```
Cannot assign `string` to `fun(_: LazyPlugin, opts: table)|true
```
What is the 2.0 way of achieving the same thing?

**Comment by lucario387** [comment]
```lua
config = function()
  vim.cmd [[UpdateRemotePlugins]]
end
```

**Comment by lucario387** [comment]
v1.0 allows string commands, v2.0 just wrap it around a function like so

**Comment by kumkee** [comment]
> ```lua
> config = function()
>   vim.cmd [[UpdateRemotePlugins]]
> end
> ```

Wow, you are lightening fast.

I got `Not an editor command: UpdateRemotePlugins`

Do I need to add quotations around the command?

**Comment by lucario387** [comment]
> Wow, you are lightening fast.

No, I just woke up

> Do I need to add quotations around the command?

The quotations in this case is the `[[]]`

> I got `Not an editor command: UpdateRemotePlugins`

Oh boi, it seems like lazy is deliberately not loading this. You can issue one at `folke/lazy.nvim`

For now, do this instead
```lua
vim.g.python3_host_prog = "result of your `which python3`"
vim.cmd([[
runtime plugin/rplugin.vim
UpdateRemotePlugins
]])
```

**Comment by lucario387** [comment]
So is it resolved? If yes then you can close this, pretty please

**Comment by kumkee** [comment]
> For now, do this instead
> 
> ```lua
> vim.g.python3_host_prog = "result of your `which python3`"
> vim.cmd([[
> runtime plugin/rplugin.vim
> UpdateRemotePlugins
> ]])
> ```

Although not elegant it works!
If you come up with a neater solution, let me know by replying to me here.

**Comment by siduck** [comment]
@kumkee neovim nightly has the semantic highlighting feature, @lucario387 wouldnt it be better for him to use it?

**Comment by lucario387** [comment]
Pyright and all OSS python LSP do not have semantic highlighting
