### ISSUE TITLE
Formatting and Floating Diagnostic don't work in Python in NvChad 2.0

### ISSUE THREAD

**Issue by kumkee** [NvChad/example_config#26]
Neither `<leader> + f` or `<leader> + fm` works for Python under NvChad 2.0
Both of them work in other languages I've tried in 2.0 and Python under NvChad 1.0.

When `<leader> + f` in a python file, 2.0 gives me
```
        a  ->  find all         o  ->  find oldfiles
        b  ->  find buffers     w  ->  live grep
        f  ->  find files
        h  ->  help page
```
While `<leader> + fm` gives nothing.

Here is my [custom directory](https://github.com/kumkee/nvchad_config).

**Comment by siduck** [comment]
@kumkee https://github.com/kumkee/nvchad_config/blob/main/configs/lspconfig.lua#L7 no pyright here

**Comment by kumkee** [comment]
> @kumkee https://github.com/kumkee/nvchad_config/blob/main/configs/lspconfig.lua#L7 no pyright here, enable it

A very stupid mistake. Thank you for the time to pinpoint it.

**Comment by lucario387** [comment]
You can revert your config to 016d32f86951ae258f3903d99ab5c24a02e1e02d

Then you just have to download pyright and it will work :)

**Comment by kumkee** [comment]
> You can revert your config to [016d32f](https://github.com/NvChad/example_config/commit/016d32f86951ae258f3903d99ab5c24a02e1e02d)
> 
> Then you just have to download pyright and it will work :)

Can you explain what `on_attach(client, bufnr)` does?
