### ISSUE TITLE
F# language support

### ISSUE THREAD

**Issue by kumkee** [NvChad/example_config#30]
This might be the wrong place to ask for help but it involves several open-source projects so here is where I likely get help.

Long story short: I want a working formatter (and perhaps a linter) for F#.

Longer versions:
- null-ls [issue#1489](https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1489)
- an existing but non-compatible solution is [Ionide-vim](https://github.com/ionide/Ionide-vim/issues/13#issuecomment-1495653961)

Please have a look and see if you, the nvchad community, can help.

**Comment by siduck** [comment]
hi @kumkee , i suppose you can just setup F# related plugins in    your custom plugins table. the example_config repo just has some basic support. I dont want to bloat it more!

**Comment by kumkee** [comment]
> hi @kumkee , i suppose you can just setup F# related plugins in your custom plugins table. the example_config repo just has some basic support. I dont want to bloat it more!

I've tried the Ionide-vim and fantomas plugin on top of the fsautocomplete lsp without luck. The reason was mentioned in the [discussion](https://github.com/ionide/Ionide-vim/issues/13#issuecomment-1495653961)
> onide-vim delegates all the LSP functionalities (including formatting) to FSAC (and thus Fantomas)

On the other hand, we use null-ls for formatting but null-ls doesn't have any F# formmaters

**Comment by siduck** [comment]
shouldnt this work? https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#fsautocomplete

**Comment by kumkee** [comment]
> shouldnt this work? https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#fsautocomplete

I don't have problems setting up LSP but a formatter. The former doesn't have formatting functionality (at least not in F#).

**Comment by siduck** [comment]
then try neoformat plugin,   you can use F# formatter with it

**Comment by kumkee** [comment]
I've got a reply from null-ls.nvim in https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1489#issuecomment-1496606157
After adding fantomas as an fsharp formatter in my null-ls fork, is the following the only thing I need to do -https://github.com/kumkee/nvchad_config/commit/406c648028f9a9e063cd3536d8d8eff0bc01d3b9?

-----------------------------------------------------------
> then try neoformat plugin, you can use F# formatter with it

I'll try neoformat if null-ls fails at the end as it's a more elegant solution.

**Comment by siduck** [comment]
@kumkee you're not allowed to edit files outside the custom dir btw!

**Comment by kumkee** [comment]
> @kumkee you're not allowed to edit files outside the custom dir btw!

The whole repo is the custom dir. Which file are you referring to? `./configs` in the repo is `custom/configs`.

**Comment by siduck** [comment]
oh nvm lul, I misread

**Comment by siduck** [comment]
btw it would be better if you added F# support to original null-ls repo, you can raise a PR there

**Comment by kumkee** [comment]
> btw it would be better if you added F# support to original null-ls repo, you can raise a PR there

Just want to try it out before sending a PR.

**Comment by siduck** [comment]
> > btw it would be better if you added F# support to original null-ls repo, you can raise a PR there
> 
> Just want to try it out before sending a PR.

does it work?

**Comment by kumkee** [comment]
> > > btw it would be better if you added F# support to original null-ls repo, you can raise a PR there
> > 
> > 
> > Just want to try it out before sending a PR.
> 
> does it work?

Frustratingly, no :(

**Comment by siduck** [comment]
its just for testing so dont add your fork in custom plugins. just change the default plugins table directly.

**Comment by kumkee** [comment]
> its just for testing so dont add your fork in custom plugins. just change the default plugins table directly.

Sorry for my ignorance.
Are you referring to `custom/plugins.lua`?
Where is the default plugins table?

**Comment by siduck** [comment]
@kumkee im referring to ~/.config/nvim/lua/plugins/init.lua

**Comment by kumkee** [comment]
> im referring to ~/.config/nvim/lua/plugins/init.lua

You don't insert `null-ls` dependency into `neovim/nvim-lspconfig` in [`~/.config/nvim/lua/plugins/init.lua`](https://github.com/NvChad/NvChad/blob/v2.0/lua/plugins/init.lua), so do I insert it there manually for testing?

**Comment by kumkee** [comment]
> > > btw it would be better if you added F# support to original null-ls repo, you can raise a PR there
> > 
> > 
> > Just want to try it out before sending a PR.
> 
> does it work?

When `:NullLsInfo`, fantomas is in the Active source list. However, `<leader> + fm` doesn't do anything.

**Comment by kumkee** [comment]
It is working now.
The problem was the LSP `fsautocomplete` only works in a proper F# project but not a single F# file.
I am closing the issue. 
Thank you, @siduck. Without your help, I wouldn't have pinpointed the problem.
