### ISSUE TITLE
Why is prettier only working with certain filetypes?

### ISSUE THREAD

**Issue by jackblackCH** [NvChad/example_config#32]
It's confusing: Why is it only working with these file types? Can't it work with javascript, typescript and jsx/react? 

from the code
 `b.formatting.prettier.with { filetypes = { "html", "markdown", "css" } }, -- so prettier works only on these filetypes`

**Comment by siduck** [comment]
@jackblackCH thats just an example! like if you want to make prettier to work only for certain fts ,  you could use that syntax.    just change that to b.formatting.prettier if you want it for all supported langs
