### ISSUE TITLE
enable all extras

### ISSUE THREAD

**Issue by mohankumargupta** [NvChad/example_config#35]
I'm a lua/neovim noob.

Currently, to enable an extras plugin, you have to add an import line at the end of plugins.lua

What lua code could I add to the end of plugins.lua to automatically import all extras plugins without having to do it one by one?

A variant I would also like is: 
  ```sh  
  if [ file in extras has a suffix of disabled, eg. trouble-disabled.lua];
  then
    don't import
  else # file is eg. trouble.lua
   automatically import
  fi  
  ```
Thanks.

**Comment by lucario387** [comment]
`{ import = "custom.plugins.extras" }`
That's all
