### ISSUE TITLE
Warning: multiple different client offset_encodings detected for buffer, this is not supported yet

### ISSUE THREAD

**Issue by adnangif** [NvChad/example_config#36]
**Description of the bug**
Warning: multiple different client offset_encodings detected for buffer, this is not supported yet

**Steps To reproduce the behavior:**

Install NvChad with example custom config
Write a code in .c or .cpp file
Write a hello world program

**System**
 Debian 12,Gnome 43.6, gnome terminal, version of nvim=0.9.0

**Comment by siduck** [comment]
not a nvchad issue, please configure your clangd custom lspconfig to silence this warning
