### ISSUE TITLE
[HELP] installing catppuccin theme

### ISSUE THREAD

**Issue by kulothunganug** [NvChad/example_config#37]
I added this in the https://github.com/NvChad/example_config/blob/4bac0fc2064ca7639c1d56c414b2d155a2b701be/plugins.lua#L49
```
  {
    "catppuccin/nvim",
    name = "catppuccin",
    priority = 1000,
    opts = {
      flavour = "latte",
    },
    config = function(_, opts)
      require("catppuccin").setup(opts)
    end
  }
}
```

and [here](https://github.com/NvChad/example_config/blob/4bac0fc2064ca7639c1d56c414b2d155a2b701be/chadrc.lua#L8) I set
```
theme = "catppuccin"
```

but the theme is not applying.

Kindly help me.

**Comment by siduck** [comment]
external themes arent allowed in nvchad, it'll break many things until you know what you're doing & requires lots of work

**Comment by kulothunganug** [comment]
thanks for the info!
